[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    name = "contact"
    success_url = "/thanks.html"

[build.processing]
  skip_processing = false

[[plugins]]
  package = "@netlify/plugin-emails"
